In [32]:
import csv
import pandas as pd

def read_csv_file(file_name):
      with open(file_name, newline='') as csv_file:           # OPENS file for reading 
        csvreader = csv.reader(csv_file, delimiter=',')     # NEWLINE='' ensures that newlines are handled properly across different operating systems
        return list(csvreader)                              #            prevents blank lines between rows 

# HERE Pokemon data is a LIST of LISt
pokemon_data = read_csv_file("pokemon_data.csv")
headers = pokemon_data[0]
rows = pokemon_data[1:]

# IF Pokemon data is a DICITONARY then just use pd.DataFrame(pokemond_data)
df = pd.DataFrame(rows, columns = headers)
df

          name base_happiness capture_rate   color    egg_group evolves_from
0      florges             70           45   white    ['fairy']      floette
1      chespin             70           45   green   ['ground']         None
2    quilladin             70           45   green   ['ground']      chespin
3     fennekin             70           45     red   ['ground']         None
4      braixen             70           45     red   ['ground']     fennekin
..         ...            ...          ...     ...          ...          ...
106    xerneas              0           45    blue  ['no-eggs']         None
107    yveltal              0           45     red  ['no-eggs']         None
108    diancie             50            3    pink  ['no-eggs']         None
109      hoopa            100            3  purple  ['no-eggs']         None
110  volcanion            100            3   brown  ['no-eggs']         None

[111 rows x 6 columns]

In [49]:
type_list = ["type_1", "type_2"]
type_dict = {"egg_group": [""]}
for i, type in enumerate(type_list):    
    if i < len(data["types"]):
            type_dict[type] = data["types"][i]["type"]["name"]    
else:        
     type_dict[type] = Nonetypes_data.append(type_dict)

NameError: name 'data' is not defined